# Build stage
FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install


COPY . .

ENV VITE_HOST=deti-tqs-23.ua.pt

# Build the app
RUN npm run build

# Production stage
FROM node:20-alpine AS prod

RUN npm install -g serve

WORKDIR /app

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
